name: Wiki Archive Bot

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 时间 02:00 (北京时间 10:00)
  workflow_dispatch:     # 允许手动触发
jobs:
  archive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mwclient python-dateutil pytz
    
    - name: Run Archive Bot
      env:
        WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
        WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
      run: |
        # 创建日志目录
        mkdir -p logs
        
        # 修改代码中的用户名密码引用方式
        sed -i "s/USERNAME = '.*'/USERNAME = os.environ['WIKI_USERNAME']/" archive_bot.py
        sed -i "s/PASSWORD = '.*'/PASSWORD = os.environ['WIKI_PASSWORD']/" archive_bot.py
        
        # 运行脚本
        python archive_bot.py
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: archive-logs
        path: logs/