name: Archive Inactive Discussions

on:
  workflow_dispatch:
    inputs:
      page_title:
        description: '页面标题'
        default: 'Zhwpwiki talk:茶馆'
        required: true
        type: string
      timeout_days:
        description: '超时天数'
        default: '30'
        required: true
        type: string

jobs:
  archive-discussions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # 根据需要选择Python版本

    - name: Install pywikibot
      run: |
        python -m pip install --upgrade pip
        pip install pywikibot

    - name: Set environment variables
      run: |
        echo "WIND_CHIMES_BOT_CONFIG=${{ secrets.WIND_CHIMES_BOT_CONFIG }}" >> $GITHUB_ENV
        echo "WIND_CHIMES_BOT_PASSWORD=${{ secrets.WIND_CHIMES_BOT_PASSWORD }}" >> $GITHUB_ENV

    - name: Run archive_inactive_discussions.py
      run: |
        python scripts/archive_inactive_discussions.py
      env:
        WIND_CHIMES_BOT_CONFIG: ${{ secrets.WIND_CHIMES_BOT_CONFIG }}
        WIND_CHIMES_BOT_PASSWORD: ${{ secrets.WIND_CHIMES_BOT_PASSWORD }}
