name: Archive Bot

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 时间 02:00

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install mwclient python-dateutil pytz

    - name: Run Archive Bot
      env:
        WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
        WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
      run: |
        python archive_bot.py